name: CI

on:
  push:
  pull_request:
    branches: [master]
jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: crystal tool format --check

  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Crystal Ameba Linter
        id: crystal-ameba
        uses: crystal-ameba/github-action@v0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Shards 
        run: shards install 
      - name: Build
        run: shards build --production --release --static --no-debug
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: curation_stats.zip
          path: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
