name: Deployment

on:
  release:
    types:
      - created

jobs:
  release_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          shards build --production --release --static --no-debug
          strip ./bin/curation_stats
      - name: Upload
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/curation_stats
          asset_name: curation_stats
          asset_content_type: binary/octet-stream
